// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AutoLaunchStatus = { enabled: boolean, method: string, 
/**
 * False on platforms with no implementation, so the UI can disable the
 * toggle rather than offer a switch that silently does nothing.
 */
supported: boolean, 
/**
 * The command line that will run at logon, when one is registered.
 */
command: string | null, };
