// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BackupRecord = { id: string, fileName: string, path: string, createdAt: string, size: bigint, sessionCount: number, };
