// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Target model per built-in category. `None` means "no target configured" and
 * the category silently does not participate.
 */
export type CategoryRouteMap = { complexCore: string | null, regularDev: string | null, visualFrontend: string | null, };
