// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ClaudeEnvEntry = { key: string, 
/**
 * Display text. For a masked entry this is a description, never the value.
 */
value: string, 
/**
 * The real value is a credential, so `value` carries only its length.
 */
masked: boolean, };
