// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClaudeEnvEntry } from "./ClaudeEnvEntry";

/**
 * What `~/.claude/settings.json` actually has in its `env` block right now.
 *
 * Read back from disk rather than recomputed from the profile. The file is
 * merged, not replaced, so what a profile *would* write and what is in effect can
 * differ: a key left behind by a previous profile, or a hand edit, shows up only
 * here.
 */
export type ClaudeEnvPreview = { 
/**
 * The file that was read, so the user can go open it.
 */
path: string, 
/**
 * `false` means Claude Code has no settings file at all — distinct from a
 * file whose `env` block is empty, which reads as `true` with no entries.
 */
exists: boolean, entries: Array<ClaudeEnvEntry>, };
