// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One client pinned to one profile.
 */
export type ClientBinding = { 
/**
 * Normalized by [`normalize_client_id`], so lookups never depend on how the
 * id was cased or padded when it was stored.
 */
clientId: string, profileId: string, 
/**
 * RFC3339. Shown in the UI and useful when a binding looks unexpected.
 */
boundAt: string, };
