// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CloudSyncResult = { success: boolean, message: string, syncedAt: string | null, };
