// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CloudSyncResult = { success: boolean, message: string, syncedAt: string | null, 
/**
 * Bytes transferred, so the UI can distinguish a real sync from a no-op.
 */
bytes: bigint | null, };
