// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Codex tool compatibility level (from Provider Deck).
 */
export type CodexToolCompat = "responses_custom" | "responses_function" | "chat_function" | "none" | "unknown";
