// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Confidence level for protocol detection and reasoning discovery.
 */
export type Confidence = "unknown" | "low" | "medium" | "high" | "certain";
