// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a consolidation pass changed.
 */
export type ConsolidateReport = { 
/**
 * Rows whose `client` spelling was rewritten to a detector id.
 */
clientsNormalized: number, 
/**
 * Rows whose timestamp was converted from Unix seconds to RFC 3339.
 */
timestampsNormalized: number, 
/**
 * Rows that gained an `identity` value.
 */
identitiesFilled: number, 
/**
 * Duplicate rows removed after being merged into a surviving row.
 */
duplicatesMerged: number, 
/**
 * Sessions remaining after the pass.
 */
sessionsAfter: number, };
