// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One keyword/regex rule. Literal rules match by substring (case-folded for
 * ASCII); regex rules compile once when the engine is built — a rule that
 * fails to compile is disabled with the reason recorded, never fatal.
 */
export type CustomRouteRule = { id: string, keyword: string, targetModel: string, isRegex: boolean, enable: boolean, };
