// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiagnosticItem } from "./DiagnosticItem";

export type DiagnosticReport = { items: Array<DiagnosticItem>, errors: number, warnings: number, okCount: number, timestamp: string, };
