// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiagnosticLevel } from "./DiagnosticLevel";

export type DiagnosticItem = { category: string, level: DiagnosticLevel, message: string, impact: string, suggestion: string, };
