// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GithubSkillSpec = { repo: string, branch: string | null, path: string | null, };
