// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionSummary } from "./SessionSummary";

export type HistoryPage = { items: Array<SessionSummary>, total: number, page: number, pageSize: number, };
