// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HistoryQuery = { client: string | null, provider: string | null, search: string | null, dateFrom: string | null, dateTo: string | null, page: number, pageSize: number, };
