// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ImportResult = { success: boolean, imported: Array<string>, skipped: Array<string>, errors: Array<string>, message: string, };
