// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type KeyDetection = { platform: string, suggestedBaseUrl: string, suggestedModel: string, confidence: number, };
