// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LatencyResult = { target: string, latencyMs: bigint | null, success: boolean, };
