// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkillSource } from "./SkillSource";

export type ManagedSkill = { id: string, name: string, description: string, source: SkillSource, enabled: boolean, };
