// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CodexToolCompat } from "./CodexToolCompat";
import type { Confidence } from "./Confidence";
import type { ModelInfo } from "./ModelInfo";
import type { ProtocolKind } from "./ProtocolKind";

export type ProbeResult = { protocol: ProtocolKind, confidence: Confidence, evidence: Array<string>, models: Array<ModelInfo>, codexCompat: CodexToolCompat, baseUrl: string, supportsStreaming: boolean, supports1mContext: boolean | null, };
