// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderConfig } from "./ProviderConfig";

export type ProfileTemplate = { id: string, name: string, description: string, provider: ProviderConfig, };
