// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderConfig } from "./ProviderConfig";

export type ProfileCreate = { name: string, providers: Array<ProviderConfig>, clients: Array<string>, };
