// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderConfig } from "./ProviderConfig";

export type ProfileUpdate = { name: string | null, providers: Array<ProviderConfig> | null, clients: Array<string> | null, gatewayEnabled: boolean | null, failoverEnabled: boolean | null, };
