// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClaudeCodeParams } from "./ClaudeCodeParams";
import type { McpServerConfig } from "./McpServerConfig";
import type { ProviderConfig } from "./ProviderConfig";

export type Profile = { id: string, name: string, providers: Array<ProviderConfig>, clients: Array<string>, mcpServers: Array<McpServerConfig>, skills: Array<string>, prompts: Array<string>, gatewayEnabled: boolean, failoverEnabled: boolean, 
/**
 * Claude Code launch parameters for this profile's clients. Profile-level
 * rather than per-provider: they configure the client process, not an
 * upstream, so a profile's clients should agree on them however many
 * providers the failover chain holds.
 */
claudeCodeParams: ClaudeCodeParams, createdAt: string, updatedAt: string, };
