// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpServerConfig } from "./McpServerConfig";
import type { ProviderConfig } from "./ProviderConfig";

export type Profile = { id: string, name: string, isActive: boolean, providers: Array<ProviderConfig>, clients: Array<string>, mcpServers: Array<McpServerConfig>, skills: Array<string>, prompts: Array<string>, gatewayEnabled: boolean, failoverEnabled: boolean, createdAt: string, updatedAt: string, };
