// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PromptScope } from "./PromptScope";

export type PromptTemplate = { id: string, name: string, content: string, variables: Array<string>, scope: PromptScope, };
