// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Detected AI protocol type.
 */
export type ProtocolKind = "openai" | "responses" | "anthropic" | "gemini" | "azure" | "unknown";
