// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CodexToolCompat } from "./CodexToolCompat";
import type { ProtocolKind } from "./ProtocolKind";
import type { RateLimitSettings } from "./RateLimitSettings";
import type { ReasoningConfidence } from "./ReasoningConfidence";

export type ProviderConfig = { id: string, name: string, baseUrl: string, protocol: ProtocolKind, defaultModel: string, models: Array<string>, isPrimary: boolean, codexCompat: CodexToolCompat, reasoningConfidence: ReasoningConfidence, acceptInvalidCerts: boolean, maxPricePerRequest: number | null, rateLimit: RateLimitSettings, };
