// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProxyToolInfo = { name: string, detected: boolean, port: number | null, running: boolean, };
