// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProxyToolInfo } from "./ProxyToolInfo";

export type ProxyStatus = { tools: Array<ProxyToolInfo>, activeProxy: string | null, httpProxy: string | null, httpsProxy: string | null, };
