// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReasoningConfidence } from "./ReasoningConfidence";

export type ReasoningInfo = { supported: boolean, confidence: ReasoningConfidence, effortLevels: Array<string>, };
