// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Reasoning confidence level (4-tier from AI Deck).
 */
export type ReasoningConfidence = "unknown" | "declared" | "validated" | "verified";
