// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How to obtain a *non-streaming* Chat Completions answer from an upstream.
 *
 * Many relays return a malformed body for a non-streaming `/chat/completions`
 * call — fields missing, or SSE frames served as a JSON body — while their
 * streaming path is correct. `Buffered` asks for a stream and reassembles it
 * into the JSON body the client expects.
 *
 * Written by `protocol::probe`, like [`CodexToolCompat`], so the user never has
 * to know this exists; the profile editor exposes it only so a wrong verdict
 * can be corrected.
 */
export type RelayChatCompat = "auto" | "buffered" | "direct";
