// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The state of the rule in one client's instructions file.
 */
export type RuleOutcome = { target: string, path: string, 
/**
 * Whether the block is present in the file, as opposed to whether the app
 * setting is on. The two diverge when the user edits the file by hand.
 */
rulePresent: boolean, 
/**
 * True when this call changed the file's bytes.
 */
changed: boolean, 
/**
 * Set when another file takes precedence and the rule will not be read.
 */
shadowedBy: string | null, 
/**
 * Set when this client's file could not be handled. The other clients are
 * still processed, so one unreadable file does not block the rest.
 */
error: string | null, };
