// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SessionSummary = { id: string, client: string, title: string, messageCount: number, totalTokens: number, createdAt: string, updatedAt: string, 
/**
 * The provider node this conversation ran against, when known.
 *
 * Recorded so switching providers or rotating a key stops looking like data
 * loss: the session stays in one list and carries where it came from, rather
 * than the app inferring provenance from whatever is configured right now.
 */
providerId: string | null, 
/**
 * The profile bound to the client when this conversation was indexed.
 */
profileId: string | null, 
/**
 * How many on-disk session files were merged into this row.
 *
 * Above 1 means the same conversation existed under several id schemes and was
 * consolidated; surfaced so a merge is visible rather than silent.
 */
mergedFrom: number, };
