// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SessionDetail = { id: string, client: string, title: string, messages: unknown[], totalTokens: bigint, createdAt: string, };
