// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SessionSummary = { id: string, client: string, title: string, messageCount: number, totalTokens: number, createdAt: string, updatedAt: string, };
