// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CategoryRouteMap } from "./CategoryRouteMap";
import type { CustomRouteRule } from "./CustomRouteRule";

/**
 * The whole smart-route layer, one instance for the app. Every field is
 * `serde(default)`-compatible so a `state.json` written before this feature
 * keeps parsing (same reason as every other `AppSettings` addition).
 */
export type SmartRouteSettings = { enableRoute: boolean, forceModel: string | null, defaultModel: string | null, fallbackEnable: boolean, modelAliasMap: { [key in string]?: string }, categoryRouteMap: CategoryRouteMap, customRules: Array<CustomRouteRule>, };
