// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SwitchResult = { success: boolean, profileId: string, profileName: string, clientsWritten: Array<string>, warnings: Array<string>, message: string, };
