// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SwitchResult = { success: boolean, profileId: string, profileName: string, 
/**
 * Clients whose config file this call actually rewrote.
 */
clientsWritten: Array<string>, 
/**
 * Clients now recorded as following this profile.
 *
 * Distinct from `clients_written`: a client with no writer of its own binds and
 * routes through the gateway but has nothing on disk to update, so it appears
 * here and not there.
 */
clientsBound: Array<string>, warnings: Array<string>, message: string, };
