// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether an upstream returns Anthropic thinking blocks a client can actually use.
 *
 * Extended thinking is only usable if each thinking block carries a `signature`.
 * Without one the client cannot persist the assistant turn or replay it, so it
 * fails the turn outright — which then strands the turn's `tool_use` with no
 * `tool_result` and poisons the rest of the session. An upstream can therefore
 * return thinking and still be unusable, which is why `Unsigned` is distinct
 * from `Absent`.
 */
export type ThinkingSupport = "unprobed" | "signed" | "unsigned" | "absent";
