// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UpdateFrequency } from "./UpdateFrequency";

export type UpdateConfig = { frequency: UpdateFrequency, lastCheck: string | null, };
