// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UsageStats = { totalSessions: number, totalMessages: number, totalTokens: number, sessionsByClient: { [key in string]?: number }, sessionsByDate: Array<[string, number]>, };
