// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReasoningConfidence } from "./ReasoningConfidence";

export type VerificationResult = { model: string, verified: boolean, confidence: ReasoningConfidence, inputTokens: bigint, outputTokens: bigint, reasoningTokens: bigint, totalTokens: bigint, message: string, };
